/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author jackdaniels
 */
public class BalcaoView extends javax.swing.JFrame {

    /**
     * Creates new form BalcaoView
     */
    public BalcaoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gerEmpButton = new javax.swing.JButton();
        gerLivroButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gerEmpButton.setText("Gerenciar Empréstimos");
        gerEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerEmpButtonActionPerformed(evt);
            }
        });

        gerLivroButton.setText("Gerenciar Livros");
        gerLivroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerLivroButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Sair");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(gerLivroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerEmpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(gerLivroButton)
                .addGap(32, 32, 32)
                .addComponent(gerEmpButton)
                .addGap(28, 28, 28)
                .addComponent(logoutButton)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerEmpButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EmprestimoView().setVisible(true);
    }//GEN-LAST:event_gerEmpButtonActionPerformed

    private void gerLivroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerLivroButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LivroView().setVisible(true);
    }//GEN-LAST:event_gerLivroButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginView().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gerEmpButton;
    private javax.swing.JButton gerLivroButton;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
